"""Initial ORM schema

Revision ID: 8f16fd464bec
Revises: 
Create Date: 2026-03-31 05:06:38.456532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f16fd464bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_conv_user'))
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_msg_conv'))
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_identities_user'))
        batch_op.drop_constraint(batch_op.f('user_identities_provider_provider_subject_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_identities_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_identity_provider_subject', ['provider', 'provider_subject'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_identity_provider_subject', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_identities_user_id'))
        batch_op.create_unique_constraint(batch_op.f('user_identities_provider_provider_subject_key'), ['provider', 'provider_subject'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_user_identities_user'), ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.create_index(batch_op.f('idx_msg_conv'), ['conversation_id'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.create_index(batch_op.f('idx_conv_user'), ['user_id'], unique=False)

    # ### end Alembic commands ###
