"""Initial ORM schema

Revision ID: 8f16fd464bec
Revises: 
Create Date: 2026-03-31 05:06:38.456532

"""
from alembic import op
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '8f16fd464bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Auto-generated migration assumed legacy indexes/constraints already existed.
    # Fresh Postgres DBs may never have had those names; only drop when present.
    conn = op.get_bind()
    insp = inspect(conn)

    def index_names(table: str) -> set[str]:
        return {ix["name"] for ix in insp.get_indexes(table)}

    def unique_names(table: str) -> set[str]:
        return {uc["name"] for uc in insp.get_unique_constraints(table)}

    if "idx_conv_user" in index_names("conversations"):
        op.drop_index("idx_conv_user", table_name="conversations")
    if "idx_msg_conv" in index_names("messages"):
        op.drop_index("idx_msg_conv", table_name="messages")
    if "idx_user_identities_user" in index_names("user_identities"):
        op.drop_index("idx_user_identities_user", table_name="user_identities")

    old_uq = "user_identities_provider_provider_subject_key"
    if old_uq in unique_names("user_identities"):
        op.drop_constraint(old_uq, "user_identities", type_="unique")

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        if "ix_conversations_user_id" not in index_names("conversations"):
            batch_op.create_index(
                batch_op.f("ix_conversations_user_id"), ["user_id"], unique=False
            )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        if "ix_messages_conversation_id" not in index_names("messages"):
            batch_op.create_index(
                batch_op.f("ix_messages_conversation_id"),
                ["conversation_id"],
                unique=False,
            )

    with op.batch_alter_table("user_identities", schema=None) as batch_op:
        if "ix_user_identities_user_id" not in index_names("user_identities"):
            batch_op.create_index(
                batch_op.f("ix_user_identities_user_id"), ["user_id"], unique=False
            )
        if "uq_user_identity_provider_subject" not in unique_names("user_identities"):
            batch_op.create_unique_constraint(
                "uq_user_identity_provider_subject",
                ["provider", "provider_subject"],
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_identity_provider_subject', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_identities_user_id'))
        batch_op.create_unique_constraint(batch_op.f('user_identities_provider_provider_subject_key'), ['provider', 'provider_subject'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_user_identities_user'), ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.create_index(batch_op.f('idx_msg_conv'), ['conversation_id'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.create_index(batch_op.f('idx_conv_user'), ['user_id'], unique=False)

    # ### end Alembic commands ###
