from __future__ import annotations

from typing import Any, Protocol


class ConversationStore(Protocol):
    """Abstract interface for conversation persistence."""

    def create(
        self, session_id: str, user_id: str, source_id: str, source_name: str
    ) -> dict: ...

    def get(self, session_id: str) -> dict | None: ...

    def get_summary(self, session_id: str) -> dict | None: ...

    def list_by_user(self, user_id: str) -> dict: ...

    def delete(self, session_id: str) -> bool: ...

    def append_message(
        self, session_id: str, role: str, content: Any, timestamp: str
    ) -> None: ...

    def update_upstream_id(
        self, session_id: str, upstream_conversation_id: str
    ) -> None: ...

    def count_by_user(self, user_id: str) -> int: ...

    def count_all(self) -> int: ...

    def delete_oldest_by_user(self, user_id: str) -> bool: ...

    def set_image_cache(self, session_id: str, images: list) -> None: ...

    def get_image_cache(self, session_id: str) -> list: ...
